os: Visual Studio 2017

version: "{build}"



configuration:
  - Release
  
environment:
  global:
    GOPATH: C:\gopath
    CMAKE_GENERATOR: Visual Studio 15 2017
  matrix:
    - GETH_ARCH: amd64
      GOARCH: amd64
      CGO_ENABLED: 1
      PATH: C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%

install:
  - echo %PATH%

build_script:
  - mkdir build
  - cd build
  - cmake -G "%CMAKE_GENERATOR% Win64" -DCMAKE_BUILD_TYPE=%CONFIGURATION% .. # Flatbuffers doesn't install flatc other than in Release.
  - cmake --build . --target install --config %CONFIGURATION%
