name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build
    - name: generate
      run: pwd && TARGET_F=../examples/simpleApp && ls $TARGET_F && cmake $TARGET_F
    - name: make
      run: cmake --build . --config Release 
    - name: install
      run: cmake --install . --config Release
