name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install requirements
      run: sudo apt install webkit2gtk-4.0
    - name: configure
      run:  mkdir build && cd build && cmake ../examples/simpleApp
    - name: make
      run: cd build && cmake --build . --config Release 
    - name: install
      run: cd build && cmake --install . --config Release
    - uses: actions/upload-artifact@v1
    with:
      name: build_linux
      path: build/
