name: CI Pipeline
on: [push]


jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev -y
      - name: Build and run tests
        run: mkdir -p build && cd build && cmake .. && cmake --build . #./script/build.sh#run: xvfb-run ./script/build.sh
      - uses: actions/upload-artifact@v1
        with:
          name: build_linux
          path: build/

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build 
        run: mkdir -p build && cd build && cmake .. && cmake --build . #./script/build.sh
      - uses: actions/upload-artifact@v1
        with:
          name: build_macos
          path: build/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build 
        run: mkdir -p build && cd build && cmake .. && cmake --build . # run: ./script/build.bat
        shell: bash
      - uses: actions/upload-artifact@v1
        with:
          name: build_windows
          path: build/
