name: CI Pipeline
on: [push]

jobs:


  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and run tests
        run: ./script/build.sh
      - uses: actions/upload-artifact@v1
        with:
          name: build_macos
          path: ./build/


  release:
    runs-on: ubuntu-latest
    needs: [build-macos]
    steps:
     
      - uses: actions/download-artifact@v1
        with:
          name: build_macos
      - run: zip -r build_macos.zip build_macos/

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: true


     

      - name: Upload Release Asset OSX
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./build_macos.zip
          asset_name: build_macos.zip
          asset_content_type: application/zip
